### ISSUE TITLE
Integrate K6 with GitHub Actions in project waltid-xyz-kit

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-xyzkit#1]

**Comment by ahmedsmiai** [comment]
The test script /src/main/test/test.js runs automatically nightly and on push or pull request from the (1-integrate-k6-with-github-actions-in-project-waltid-xyz-kit) branch, 
it verifies the test cases and returns the results in a format of html file, the result is stored as an artifact 


![Image](https://user-images.githubusercontent.com/47064156/215623867-1f99a18c-e0e8-459d-afee-b406aad1507f.png)



In case of a test or a job failure, an email will be sent to my email, can be configured in .github/workflows/load-test.yml

**Comment by philpotisk** [comment]
> it verifies the test cases and returns the results in a format of html file

where and how can the results be reviewed?

**Comment by ahmedsmiai** [comment]
@philpotisk under each load-testing workflow run you can find an artifact, you just download it and open the html file in a browser


![Image](https://user-images.githubusercontent.com/47064156/215736048-53863736-75b5-4976-bfd9-15ab2fada5b4.png)

or you can view the results in the console log of K6 by going to 



![Image](https://user-images.githubusercontent.com/47064156/215736854-27ba08d3-40c9-4600-b29e-476c810d452d.png)



![Image](https://user-images.githubusercontent.com/47064156/215736986-8b123faa-47b3-475a-9d5c-3f0ee8f50a65.png)
